import { Department } from './department.model';
import { User } from './user.model';
import { Student } from './student.model';
import { ProjectProgress } from './project-progress.model';
import { ManagerStaff } from './manager-staff.model';
import { ReviewerStaff } from './reviewer-staff.model';
import { ExaminerCouncil } from './examiner-council.model';
import { Semester } from './semester.model';
import { ProjectStatus } from '../constants';

export interface Project {
    id?: number;
    createdAt?: Date;
    updatedAt?: Date;
    name?: string;
    description?: string;
    requirement?: string;
    status?: ProjectStatus;
    semester?: Semester;
    semesterId?: number;
    departmentId?: number;
    department?: Department;
    instructorId?: number;
    instructor?: User;
    proposeBy?: User;
    proposeById?: number;
    students?: Student[];
    instructorName?: string;
    studentCodes?: string;
    progresses?: ProjectProgress[];
    isManager?: boolean;
    isInstructor?: boolean;
    isReviewer?: boolean;
    isCouncilManager?: boolean;
    managerStaffId?: number;
    managerStaff?: ManagerStaff;
    reviewerStaff?: ReviewerStaff;
    reviewerStaffId?: number;
    reviewedById?: number;
    reviewedBy?: User;
    examinerCouncil?: ExaminerCouncil;
    formScore?: number;
    contentScore?: number;
    summarizeScore?: number;
    answerScore?: number;
    conclusionScore?: number;
    reportedCount?: number;
}
